{% set version = "0.5.30" %}

package:
  name: pypfb
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pypfb/pypfb-{{ version }}.tar.gz
  sha256: 7bcb16444898246bf445b5efad5c672af8d23a7a5dcfeeaca1ac13c40d502175

build:
  number: 0
  noarch: python
  entry_points:
    - pfb = pfb.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - poetry
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - click
    - fastavro >=1.8.2,<1.9.0
    - python-json-logger
    - pyyaml
    - importlib-metadata
    - gen3dictionary
    - aiohttp
    - dictionaryutils
    - gen3

test:
  commands:
    - pip check
    - pfb --help
  imports:
    - pfb
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/uc-cdis/pypfb
  summary: Python SDK for PFB format
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
