{% set version = "0.5.32" %}

package:
  name: pypfb
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pypfb/pypfb-{{ version }}.tar.gz
  sha256: 8c382731f16da8afd70a8dc3cba2474e1bd890a71bb217402d057a13311e7da4

build:
  number: 0
  noarch: python
  entry_points:
    - pfb = pfb.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - poetry
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - click
    - fastavro >=1.8.2,<1.9.0
    - python-json-logger
    - pyyaml
    - importlib-metadata
    - gen3dictionary
    - aiohttp
    - dictionaryutils
    - gen3

test:
  commands:
    - pip check
    - pfb --help
  imports:
    - pfb
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/uc-cdis/pypfb
  summary: Python SDK for PFB format
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
