schema_version: 1

context:
  version: "0.5.33"

package:
  name: pypfb
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pypfb/pypfb-${{ version }}.tar.gz
  sha256: 00b1a78b75d670b9dcdb85dfac78dce10594834ad8cd2e89ae60fdd3efad017b

build:
  number: 0
  noarch: python
  script:
    - sed -i '/gen3= /d' pyproject.toml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pfb = pfb.cli:main

requirements:
  host:
    - python =${{ python_min }}
    - poetry
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - click
    - fastavro >=1.8.2,<1.9.0
    - python-json-logger
    - pyyaml
    - importlib-metadata
    - gen3dictionary
    - aiohttp
    - dictionaryutils
    - gen3

tests:
  - python:
      imports:
        - pfb
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check
      - pfb --help

about:
  summary: Python SDK for PFB format
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/uc-cdis/pypfb

extra:
  recipe-maintainers:
    - danielnachun
